### ISSUE TITLE
Redeploy

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/startup-week#16]
@grungerabbit I updated the date for Spring's Startup Week. Can you redeploy?

**Comment by grungerabbit** [comment]
I can redeploy stuff 1/16. If anyone can get to it before then, that'd be great! Otherwise I'll put it up next week

**Comment by grungerabbit** [comment]
bringing this up again because I dropped the ball and don't have access to the server anymore. @AbhiAgarwal can you set up a githook for master? I added some more copy changes just now.

**Comment by AbhiAgarwal** [comment]
@grungerabbit @ethanresnick: this now exists on Rackspace Cloud Files. The server is no longer important. 

The speed/load times are much much much better b/c of this, and this will fix all of our problems. Please text/slack me if anything needs to be deployed.

A githook for master will be setup by Friday. (When I get back to the U.S.) Till then please just forward it to me - I have a script to just upload everything

**Comment by ethanresnick** [comment]
@AbhiAgarwal How does the cron job that was polling the api for the latest data and then rebuilding the site fit into this? (We need to be able to have the site fetch updated API data automatically, so that last minute SW changes the team makes are reflected ASAP.)

**Comment by AbhiAgarwal** [comment]
@ethanresnick Well the process for the githook is to rebuild the jekyll and then upload that onto rackspace using an upload script. Same reason would apply for the fetch cron job. Would just rebuild and upload - no problem.

**Comment by ethanresnick** [comment]
Right, I just want to make sure the cron job is still running under the new setup.

**Comment by AbhiAgarwal** [comment]
@ethanresnick yes it's running. Just need to modify:

https://github.com/TechAtNYU/startup-week/blob/master/_scripts/process.js

To match the new ID and I think we will be fine.
