### ISSUE TITLE
text overlap on mobile

### ISSUE THREAD

**Issue by terriburns** [TechAtNYU/startup-week#34]
![img_8897](https://cloud.githubusercontent.com/assets/7284203/13939288/2a52cdb6-efaa-11e5-88b5-71fe6b04ad93.jpg)

**Comment by oa495** [comment]
can you give it a look now?

**Comment by terriburns** [comment]
it's the same

**Comment by oa495** [comment]
once more ? :smile:

**Comment by terriburns** [comment]
lgtm! yay! you're great :+1:
